disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Carlos's Website"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "FaCE.png"

[params.author]
name="Carlos A. Lugo Ph.D."
headline = "Physics, Maths and Computers."
links = [ { hackster = "https://www.hackster.io/kupkasmale" }, { github = "https://github.com/calugo" }, { gitlab = "https://gitlab.com/calugo" }, { linkedin = "https://linkedin.com/in/carlos-a-lugo-velez" }, { orcid = "https://orcid.org/0000-0003-0095-566X" } ]
image = "FaCe.png"